### ISSUE TITLE
initialze an app inspector controller

### ISSUE THREAD

**Issue by johrstrom** [OSC/osc-reporting#31]
initialze an app inspector controller with an `#index` that shows a simple histogram shown in #23 that's preset to `sys/bc_osc_jupyter` with say 5 bins.  The navbar should add a link to this page.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202307486806032) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
Closed in #35
