### ISSUE TITLE
add dropdown to app inspector

### ISSUE THREAD

**Issue by johrstrom** [OSC/osc-reporting#32]
Given the page and controller in #31 - this ticket is to add a dropdown menu to choose the app you want to inspect. When a new app is selected, the histogram panel should update accordingly.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202307534013383) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
Closed in #39
