### ISSUE TITLE
request through actioncable

### ISSUE THREAD

**Issue by johrstrom** [OSC/osc-reporting#43]
I think we got hung up on REST and websockets precisely because they're different protocols.

What if the flow was more like REST controllers generate static pages and any updates are requested and published through websockets. 

I'm wondering what it would look like if we made requests through actionable in javascipt.

* handle the 'on change' event
* send a websocket message something like `{ action: 'replace', id: 'app_inspector_histogram' }` (IDK what the interface is here, but simplicity is good and maybe it's even just `{ action: 'run_this_function' }` and then we just call a `run_this_function` on the thing listening).
* The rails app responds to this message by broadcasting the replace message (much like the system status panels do now)

So the slider `'on change'` wouldn't make an HTTP request it'd send a websocket message that the rails app would then broadcast another.  So there's no (or at least less) bleed from HTTP -> web sockets. static page are requested & shown over HTTP and all updates happen through websockets.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202382969344883) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
@johrstrom I'm finding that using this method adds a lot more complexity because we have to create an actioncable instance, a new channel, a client on the frontend and new methods for things that turbo would handle automatically. Is there a different way of accessing websockets that I am unaware of or is this the right way to go?

**Comment by johrstrom** [comment]
> I'm finding that using this method adds a lot more complexity because we have to create an actioncable instance, a new channel, a client on the frontend and new methods for things that turbo would handle automatically. Is there a different way of accessing websockets that I am unaware of or is this the right way to go? 

I'd guess what you're finding is the right track. I would like to _see_ what it would look like/entail anyhow.

> Do we actually want to move away from the built-in way of turbo-streams?

🤷  Let's see what we see then decide. I'm not sold on it either, but if it gave us some better building blocks.  There will be more code sure, but if our mental model can compartmentalize it better that may be a win.

In any case, this project is exploratory and this ticket even more so.  I don't want to do it for sure, I just want to see what it would look like.
